In [1]:
import numpy as np

In [9]:
#Problem 1: Normalization Problem

#Initialization
X = np.random.random((5,5))

#Creating a function defining normalization
def normalize(x): #using a function simplify things for me
    z = (x-x.mean())/x.std() #Using the formula given in the experiment
    np.save('X_normalized.npy', z) #Saving file 
    print(np.load('X_normalized.npy')) #Print using the saved file

normalize(X) #Output check

[[ 1.26793827  0.42717441 -1.7215295  -0.18352278 -0.60224866]
 [ 0.68491049  1.61266095  1.05607218  1.6119995  -0.88023778]
 [-1.0775551  -1.85939689  0.60483001  0.25310663 -0.14600764]
 [-1.20843784  0.14908656 -0.46947158  1.61024671 -0.59852694]
 [-0.52374409 -0.347465    0.67938685 -1.07888076  0.739612  ]]


In [10]:
#Problem 2: Divisible by 3 Problem

#Initialization
A = np.arange(1,101) ** 2 #Create an array of squares
A = A.reshape(10,10)#Reshaping to 10x10 per instructions

#Using this equation too find values divisible by 3
B = A[A%3==0]#Searching for values of A that are divisible by 3 
np.save('div_by_3.npy', B)#Saved as .npy file per instructions

print(B)#Output check using B

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
